/*
 * Open Teradata Viewer ( test editor xml tools )
 * Copyright (C), D. Campione
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package test.net.sourceforge.open_teradata_viewer.editor.xml_tools;

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;

import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;

import org.junit.jupiter.api.Test;
import org.xml.sax.SAXException;

import net.sourceforge.open_teradata_viewer.editor.xml_tools.XMLBeautifier;

/**
 * 
 * 
 * @author D. Campione
 *
 */
public class TestXMLBeautifier {

    /**
     * The line separator {@link XMLBeautifier#indentXML(String)} itself inserts
     * (via the JDK's built-in JAXP Transformer) is whatever the current platform's
     * is - never a literal "\r\n", even on Windows, where it does happen to match.
     * Building expected strings with this instead of a hardcoded "\r\n" keeps these
     * tests passing on any OS.
     */
    private static final String LS = System.lineSeparator();

    @Test
    public void test_indentXML_defaultConstructor()
            throws SAXException, IOException, ParserConfigurationException, TransformerException {
        XMLBeautifier xmlBeautifier = new XMLBeautifier();
        String unformattedXML = "<note><body></body></note>";
        unformattedXML = xmlBeautifier.validateXML(unformattedXML);
        String formattedXML = xmlBeautifier.indentXML(unformattedXML);
        String expectedPrefix = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><note>";
        assertTrue(formattedXML.startsWith(expectedPrefix));
    }

    @Test
    public void test_indentXML_returnCarriageAndSpaces()
            throws SAXException, IOException, ParserConfigurationException, TransformerException {
        XMLBeautifier xmlBeautifier = new XMLBeautifier(XMLBeautifier.DEFAULT_TAB_SIZE);
        String unformattedXML = "    <note>\r\n"
                + "<to>Tove</to><from>Jani</from><heading>Reminder</heading>            <body>Don't forget me this weekend!\r\n"
                + "</body></note>";
        String formattedXML = xmlBeautifier.indentXML(unformattedXML);
        String expectedPrefix = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><note>";
        assertTrue(formattedXML.startsWith(expectedPrefix));

        // NOTE: this is indentXML() called directly on irregular,
        // un-normalized XML (no validateXML() pass first) - not a path any
        // real caller in OTV actually takes (IndentXMLAction always calls
        // validateXML() first; ExportPreviewer's XML is generated by OTV
        // itself, never raw/irregular like this). The exact placement of
        // "insignificant" whitespace text nodes between elements in a case
        // like this is an internal JAXP/Xalan serializer heuristic, and it
        // is genuinely different on Java 11's bundled implementation than
        // whatever produced the previous version of this expected string
        // (most likely Java 8's) - reproduced and confirmed using nothing
        // but the JDK's own javax.xml.transform classes directly, with no
        // OTV code involved, so this is a JDK-version artifact of this one
        // synthetic edge case, not a regression in XMLBeautifier itself.
        String expected = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><note>" + LS + "    " + LS + "    <to>Tove</to>"
                + LS + "    <from>Jani</from>" + LS + "    <heading>Reminder</heading>" + LS + "                " + LS
                + "    <body>Don't forget me this weekend!" + LS + "</body>" + LS + "</note>" + LS;
        assertTrue(formattedXML.equals(expected));

        formattedXML = xmlBeautifier.validateXML(formattedXML);
        formattedXML = xmlBeautifier.indentXML(formattedXML);
        expected = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><note>" + LS + "    <to>Tove</to>" + LS
                + "    <from>Jani</from>" + LS + "    <heading>Reminder</heading>" + LS
                + "    <body>Don't forget me this weekend!</body>" + LS + "</note>" + LS;
        assertTrue(formattedXML.equals(expected));
    }

    @Test
    public void test_indentXML_negativeTabSize()
            throws SAXException, IOException, ParserConfigurationException, TransformerException {
        XMLBeautifier xmlBeautifier = new XMLBeautifier(-1);
        String unformattedXML = "    <note>\r\n"
                + "<to>Tove</to><from>Jani</from><heading>Reminder</heading>            <body>Don't forget me this weekend!\r\n"
                + "</body></note>";
        unformattedXML = xmlBeautifier.validateXML(unformattedXML);
        String formattedXML = xmlBeautifier.indentXML(unformattedXML);
        String expected = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><note>" + LS + "    <to>Tove</to>" + LS
                + "    <from>Jani</from>" + LS + "    <heading>Reminder</heading>" + LS
                + "    <body>Don't forget me this weekend!</body>" + LS + "</note>" + LS;
        assertTrue(formattedXML.equals(expected));
    }
}
