/*
 * Open Teradata Viewer ( sql parser )
 * Copyright (C) 2013, D. Campione
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package net.sourceforge.open_teradata_viewer.sqlparser.parser;

import java.io.Reader;

import net.sourceforge.open_teradata_viewer.sqlparser.SQLParserException;
import net.sourceforge.open_teradata_viewer.sqlparser.statement.IStatement;

/**
 * A ISqlParser implementation that uses a parser generated by JavaCC.
 * 
 * @author D. Campione
 * 
 */
public class CCSqlParserManager implements ISqlParser {

    @Override
    public IStatement parse(Reader statementReader) throws SQLParserException {
        CCSqlParser parser = new CCSqlParser(statementReader);
        try {
            return parser.IStatement();
        } catch (Exception ex) {
            throw new SQLParserException(ex);
        }
    }
}