/* Generated By:JavaCC: Do not edit this line. CCSqlParserTreeConstants.java Version 5.0 */
package net.sourceforge.open_teradata_viewer.sqlparser.parser;

public interface CCSqlParserTreeConstants
{
  public int JJTSTATEMENT = 0;
  public int JJTSINGLESTATEMENT = 1;
  public int JJTSTATEMENTS = 2;
  public int JJTSET = 3;
  public int JJTUPDATE = 4;
  public int JJTREPLACE = 5;
  public int JJTLISTEXPRESSIONITEM = 6;
  public int JJTINSERT = 7;
  public int JJTDELETE = 8;
  public int JJTCOLUMN = 9;
  public int JJTRELOBJECTNAME = 10;
  public int JJTRELOBJECTNAMEEXT = 11;
  public int JJTTABLE = 12;
  public int JJTTABLEWITHALIAS = 13;
  public int JJTSELECT = 14;
  public int JJTSELECTBODY = 15;
  public int JJTPLAINSELECT = 16;
  public int JJTSETOPERATIONLIST = 17;
  public int JJTWITHLIST = 18;
  public int JJTWITHITEM = 19;
  public int JJTSELECTITEMSLIST = 20;
  public int JJTSELECTEXPRESSIONITEM = 21;
  public int JJTSELECTITEM = 22;
  public int JJTALLTABLECOLUMNS = 23;
  public int JJTALIAS = 24;
  public int JJTFUNCTIONITEM = 25;
  public int JJTPIVOTFORCOLUMNS = 26;
  public int JJTPIVOTFUNCTIONITEMS = 27;
  public int JJTPIVOTSINGLEINITEMS = 28;
  public int JJTEXPRESSIONLISTITEM = 29;
  public int JJTPIVOTMULTIINITEMS = 30;
  public int JJTPIVOT = 31;
  public int JJTPIVOTXML = 32;
  public int JJTINTOCLAUSE = 33;
  public int JJTFROMITEM = 34;
  public int JJTVALUESLIST = 35;
  public int JJTLATERALSUBSELECT = 36;
  public int JJTSUBJOIN = 37;
  public int JJTJOINSLIST = 38;
  public int JJTJOINEREXPRESSION = 39;
  public int JJTWHERECLAUSE = 40;
  public int JJTORACLEHIERARCHICALQUERYCLAUSE = 41;
  public int JJTGROUPBYCOLUMNREFERENCES = 42;
  public int JJTHAVING = 43;
  public int JJTORDERBYELEMENTS = 44;
  public int JJTORDERBYELEMENT = 45;
  public int JJTLIMIT = 46;
  public int JJTOFFSET = 47;
  public int JJTFETCH = 48;
  public int JJTTOP = 49;
  public int JJTSKIP = 50;
  public int JJTFIRST = 51;
  public int JJTEXPRESSION = 52;
  public int JJTOREXPRESSION = 53;
  public int JJTANDEXPRESSION = 54;
  public int JJTCONDITION = 55;
  public int JJTREGULARCONDITION = 56;
  public int JJTSQLCONDITION = 57;
  public int JJTINEXPRESSION = 58;
  public int JJTBETWEEN = 59;
  public int JJTLIKEEXPRESSION = 60;
  public int JJTISNULLEXPRESSION = 61;
  public int JJTEXISTSEXPRESSION = 62;
  public int JJTSQLEXPRESSIONLIST = 63;
  public int JJTSIMPLEEXPRESSIONLIST = 64;
  public int JJTSIMPLEEXPRESSIONLISTATLEASTTWOITEMS = 65;
  public int JJTCOMPARISONITEM = 66;
  public int JJTALLCOMPARISONEXPRESSION = 67;
  public int JJTANYCOMPARISONEXPRESSION = 68;
  public int JJTSIMPLEEXPRESSION = 69;
  public int JJTCONCATEXPRESSION = 70;
  public int JJTBITWISEANDOR = 71;
  public int JJTADDITIVEEXPRESSION = 72;
  public int JJTMULTIPLICATIVEEXPRESSION = 73;
  public int JJTBITWISEXOR = 74;
  public int JJTPRIMARYEXPRESSION = 75;
  public int JJTJDBCNAMEDPARAMETER = 76;
  public int JJTUSERVARIABLE = 77;
  public int JJTNUMERICBIND = 78;
  public int JJTJSONEXPRESSION = 79;
  public int JJTINTERVALEXPRESSION = 80;
  public int JJTWITHINGROUPEXPRESSION = 81;
  public int JJTKEEPEXPRESSION = 82;
  public int JJTANALYTICEXPRESSION = 83;
  public int JJTWINDOWELEMENT = 84;
  public int JJTWINDOWOFFSET = 85;
  public int JJTEXTRACTEXPRESSION = 86;
  public int JJTCASTEXPRESSION = 87;
  public int JJTCASEWHENEXPRESSION = 88;
  public int JJTWHENTHENSEARCHCONDITION = 89;
  public int JJTWHENTHENVALUE = 90;
  public int JJTROWCONSTRUCTOR = 91;
  public int JJTEXECUTE = 92;
  public int JJTFUNCTION = 93;
  public int JJTMYSQLGROUPCONCAT = 94;
  public int JJTSUBSELECT = 95;
  public int JJTCREATEINDEX = 96;
  public int JJTCREATETABLE = 97;
  public int JJTCOLDATATYPE = 98;
  public int JJTCREATEVIEW = 99;
  public int JJTCREATEPARAMETER = 100;
  public int JJTALIST = 101;
  public int JJTCOLUMNSNAMESLIST = 102;
  public int JJTDROP = 103;
  public int JJTTRUNCATE = 104;
  public int JJTALTER = 105;


  public String[] jjtNodeName = {
    "Statement",
    "SingleStatement",
    "Statements",
    "Set",
    "Update",
    "Replace",
    "ListExpressionItem",
    "Insert",
    "Delete",
    "Column",
    "RelObjectName",
    "RelObjectNameExt",
    "Table",
    "TableWithAlias",
    "Select",
    "SelectBody",
    "PlainSelect",
    "SetOperationList",
    "WithList",
    "WithItem",
    "SelectItemsList",
    "SelectExpressionItem",
    "SelectItem",
    "AllTableColumns",
    "Alias",
    "FunctionItem",
    "PivotForColumns",
    "PivotFunctionItems",
    "PivotSingleInItems",
    "ExpressionListItem",
    "PivotMultiInItems",
    "Pivot",
    "PivotXml",
    "IntoClause",
    "FromItem",
    "ValuesList",
    "LateralSubSelect",
    "SubJoin",
    "JoinsList",
    "JoinerExpression",
    "WhereClause",
    "OracleHierarchicalQueryClause",
    "GroupByColumnReferences",
    "Having",
    "OrderByElements",
    "OrderByElement",
    "Limit",
    "Offset",
    "Fetch",
    "Top",
    "Skip",
    "First",
    "Expression",
    "OrExpression",
    "AndExpression",
    "Condition",
    "RegularCondition",
    "SQLCondition",
    "InExpression",
    "Between",
    "LikeExpression",
    "IsNullExpression",
    "ExistsExpression",
    "SQLExpressionList",
    "SimpleExpressionList",
    "SimpleExpressionListAtLeastTwoItems",
    "ComparisonItem",
    "AllComparisonExpression",
    "AnyComparisonExpression",
    "SimpleExpression",
    "ConcatExpression",
    "BitwiseAndOr",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "BitwiseXor",
    "PrimaryExpression",
    "JdbcNamedParameter",
    "UserVariable",
    "NumericBind",
    "JsonExpression",
    "IntervalExpression",
    "WithinGroupExpression",
    "KeepExpression",
    "AnalyticExpression",
    "WindowElement",
    "WindowOffset",
    "ExtractExpression",
    "CastExpression",
    "CaseWhenExpression",
    "WhenThenSearchCondition",
    "WhenThenValue",
    "RowConstructor",
    "Execute",
    "Function",
    "MySQLGroupConcat",
    "SubSelect",
    "CreateIndex",
    "CreateTable",
    "ColDataType",
    "CreateView",
    "CreateParameter",
    "AList",
    "ColumnsNamesList",
    "Drop",
    "Truncate",
    "Alter",
  };
}
/* JavaCC - OriginalChecksum=4f886056eff12ebf59c025d8d85f2d14 (do not edit this line) */
